In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving mega_data_cleaning_dataset.xlsx to mega_data_cleaning_dataset.xlsx

In [ ]:
df = pd.read_excel("mega_data_cleaning_dataset.xlsx")
print(df.head())

   Customer_ID           Name  Age  Gender      Country     State  \
0         1191  Larry Wallace   31   Other          NaN  Arkansas
1         8287   Shawn Palmer   20    Male       Uganda     Texas
2         6574  Daniel Cortez  105     Mle   Tajikistan   Montana
3         3377   Cindy Barber  100  Female        Chile      Ohio
4         5107  William Patel  110     Mle  Timor-Leste    Hawaii

                 City                               Email Signup_Date  \
0           Janetfort  gonzalezbrandi@shaffer-lambert.com  2021-05-23
1          Smithhaven            davidmendoza@hotmail.com  2025-05-18
2  West Jennifermouth               hoffmancole@yahoo.com  2025-05-19
3          Staceyberg            carpenterlinda@yahoo.com  2024-08-19
4     South Hollyfort     blairivan@lyons-christensen.org  2020-05-04

  Account_Status  ...  Quantity Purchase_Date Delivery_Date  Payment_Type  \
0       Inactive  ...        12    2025-04-04    2025-09-10            up
1            NaN  ...         9    2025-01-23    2025-05-29          Cash
2         Active  ...         0    2025-08-08    2025-01-30           UPI
3         Active  ...         9    2025-03-25    2025-01-24         Debit
4            NaN  ...         7    2025-05-04    2025-04-26            up

   Feedback_Score                                       Comments  \
0             4.7                       During about main range.
1             4.2  Beat increase state especially society color.
2             3.7                           That resource sound.
3             4.4             Customer international base media.
4             2.5                          Sport concern entire.

  Customer_Loyalty Last_Login Signup_Channel  Total_Purchase
0              NaN 2025-07-23            Web         7394.28
1        Returning 2025-02-21            Web         5083.20
2        Returning 2025-04-24            web            0.00
3              New 2025-07-28            App         7361.37
4              New        NaT            App         6561.10

[5 rows x 25 columns]

In [ ]:
df.shape

(10000, 25)

In [ ]:
df.drop_duplicates(inplace=True)
df.shape

(10000, 25)

In [ ]:
df.drop_duplicates(subset="Customer_ID", inplace=True)
df.shape

(6172, 25)

In [ ]:
df.drop_duplicates(subset="Email", inplace=True)
df.shape

(5824, 25)

In [ ]:
df.drop_duplicates(subset="Product_ID", inplace=True)
df.shape

(500, 25)

In [ ]:
df["Name"].fillna("Unknown", inplace=True)

/tmp/ipython-input-626038248.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].fillna("Unknown", inplace=True)

In [ ]:
df["Email"].fillna("noemail@example.com", inplace=True)

/tmp/ipython-input-4185083826.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Email"].fillna("noemail@example.com", inplace=True)

In [ ]:
df["Product_Name"].fillna("Misc", inplace=True)

/tmp/ipython-input-172078916.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Product_Name"].fillna("Misc", inplace=True)

In [ ]:
df["Category"].fillna("Misc", inplace=True)

/tmp/ipython-input-862680720.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Category"].fillna("Misc", inplace=True)

In [ ]:
df["Feedback_Score"].fillna(df.groupby("Product_ID")["Feedback_Score"].transform("median"), inplace=True)

/tmp/ipython-input-3538454351.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Feedback_Score"].fillna(df.groupby("Product_ID")["Feedback_Score"].transform("median"), inplace=True)

In [ ]:
df["Quantity"].fillna(1, inplace=True)

/tmp/ipython-input-836767623.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Quantity"].fillna(1, inplace=True)

In [ ]:
df = df[df["Price"]>0]

In [ ]:
df = df[df["Quantity"]>0]

In [ ]:
df = df[(df['Age'] >= 0) & (df['Age'] <= 120)]

In [ ]:
df = df[df['Delivery_Date'] >= df['Purchase_Date']]

In [ ]:
df['Gender'] = df['Gender'].replace({'Mle':'Male','m':'Male','f':'Female','F':'Female'})

In [ ]:
df['Payment_Type'] = df['Payment_Type'].replace({'crdit':'Credit Card','deb':'Debit Card'})

In [ ]:
df['Account_Status'] = df['Account_Status'].str.capitalize().replace({'Act':'Active','Inact':'Inactive'})

In [ ]:
df.shape

(150, 25)

In [ ]:
df[df['Price'] > 500]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
17,5598,Michelle Case,6,Other,NaN,Montana,Christopherfurt,sullivanjared@hotmail.com,2025-07-29,Banned,...,17,2025-01-03,2025-09-04,Debit,3.9,Describe again response machine remember.,VIP,2025-09-22,App,11291.74
24,1619,Michael Shelton,11,Other,Mauritania,Idaho,Johnsonbury,jasonthomas@everett.com,2022-11-15,Banned,...,8,2025-04-12,2025-06-02,Cash,1.7,Analysis article sometimes Mr.,New,2025-02-21,web,7102.96
31,116,Kathy Hernandez,103,Female,Lebanon,North Dakota,Barreramouth,jmoon@fitzpatrick.com,2021-02-23,Banned,...,5,2025-08-07,2025-09-23,up,3.8,Store base opportunity yeah activity.,New,2025-05-23,Web,3578.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1615,7675,Kyle Watts,105,Male,Andorra,Hawaii,East Elizabeth,josephwhite@gmail.com,2022-04-26,Banned,...,3,2025-06-25,2025-10-12,Cash,4.7,Why address see work.,New,NaT,App,2300.55
1686,579,Jeremy Mayo,30,Other,Bosnia and Herzegovina,Alaska,Dennisland,devonhoover@johnson.com,2023-12-10,Banned,...,14,2025-05-25,2025-06-10,Crdit,4.9,NaN,VIP,2025-01-22,app,12697.58
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,UPI,4.1,NaN,VIP,NaT,App,7556.40
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84

In [ ]:
df[df["Feedback_Score"] < 3]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
14,8372,Samuel Mcgee,0,Male,Martinique,New Jersey,Burkechester,tyler96@hotmail.com,2023-11-01,Active,...,18,2025-07-07,2025-09-24,Debit,2.2,Term meeting one statement role long campaign.,New,2025-03-11,Phone,4285.26
24,1619,Michael Shelton,11,Other,Mauritania,Idaho,Johnsonbury,jasonthomas@everett.com,2022-11-15,Banned,...,8,2025-04-12,2025-06-02,Cash,1.7,Analysis article sometimes Mr.,New,2025-02-21,web,7102.96
30,930,Nicole Gomez,51,Male,Uzbekistan,Colorado,East Susan,spencerwilliam@tran.com,2021-06-29,NaN,...,4,2025-05-21,2025-09-20,Cash,1.4,Security per design special woman fall above.,VIP,2025-04-21,web,1935.12
43,1738,James Haas,54,Male,Mauritania,New York,Lake Amandafort,ebrown@martinez.net,2020-06-20,Banned,...,9,2025-06-21,2025-08-22,Debit,2.4,There draw recent company deal.,New,2025-03-17,Phone,6598.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2131,5006,Phillip Graves,46,Male,NaN,Hawaii,Thompsonland,patrickjohnson@hotmail.com,2021-02-17,Active,...,13,2025-02-23,2025-08-06,Debit,0.5,Man Congress officer room allow.,Returning,2025-02-26,Web,3579.55
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56

In [ ]:
df[(df["Customer_Loyalty"]== "VIP") & (df["Total_Purchase"] > 1000)]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
17,5598,Michelle Case,6,Other,NaN,Montana,Christopherfurt,sullivanjared@hotmail.com,2025-07-29,Banned,...,17,2025-01-03,2025-09-04,Debit,3.9,Describe again response machine remember.,VIP,2025-09-22,App,11291.74
30,930,Nicole Gomez,51,Male,Uzbekistan,Colorado,East Susan,spencerwilliam@tran.com,2021-06-29,NaN,...,4,2025-05-21,2025-09-20,Cash,1.4,Security per design special woman fall above.,VIP,2025-04-21,web,1935.12
70,7091,Unknown,50,Female,Myanmar,Kentucky,Port Kendra,zmiller@hotmail.com,2022-01-17,NaN,...,10,2025-06-18,2025-08-31,Credit,0.1,Course positive new fire sell policy.,VIP,2025-01-25,App,3098.20
87,3947,Shelly Bailey,109,Male,Bahamas,Georgia,North Michaelbury,ashleyshelton@hotmail.com,2025-06-19,Active,...,5,2025-09-11,2025-09-20,up,4.7,Sure if everything fly the wonder.,VIP,2025-05-27,web,2906.70
89,6219,Marie Williams,6,Male,New Caledonia,Wyoming,Samuelberg,matajohn@sandoval.com,2023-11-05,NaN,...,16,2025-01-14,2025-01-27,Cash,5.5,Away necessary bad hotel run.,VIP,2025-08-15,App,12443.04
91,8892,Sara Rodriguez,78,Female,Libyan Arab Jamahiriya,Ohio,New Gerald,amorgan@hotmail.com,2020-07-08,Inactive,...,2,2025-05-14,2025-06-13,Crdit,5.0,Join style none stock put instead pressure stu...,VIP,2025-04-24,Phone,1856.54
112,3340,Anthony Jacobs,7,Female,French Polynesia,Pennsylvania,West Amy,reedjared@hotmail.com,2022-05-18,NaN,...,15,2025-08-28,2025-09-01,Credit,4.1,NaN,VIP,2025-06-06,App,7436.10
122,2361,Douglas Noble,80,Female,Turks and Caicos Islands,Colorado,West Glen,tlopez@rivera-garcia.info,2021-08-01,NaN,...,15,2025-01-07,2025-01-22,up,4.0,Other network many nor country.,VIP,2025-07-08,app,7429.35
132,5445,Christopher Taylor,61,Other,Antarctica (the territory South of 60 deg S),Delaware,North Candiceshire,matthew90@baker-butler.com,2021-03-25,Banned,...,2,2025-06-14,2025-07-22,Cash,0.2,NaN,VIP,2025-06-19,Web,1585.76
163,9228,Jennifer Garrett DDS,38,Male,Pitcairn Islands,Arizona,East Jonathanville,creynolds@lamb.biz,2024-03-03,Inactive,...,3,2025-02-17,2025-06-07,Crdit,5.3,Care decision thus term senior stand fill.,VIP,2025-08-24,Web,2781.36
175,403,Stacey Gilmore,108,Male,Malaysia,Mississippi,Gutierrezchester,evanslaurie@yahoo.com,2023-03-02,Active,...,15,2025-02-23,2025-07-15,Credit,5.1,NaN,VIP,2025-07-05,Web,2904.60
189,5574,Cynthia Cunningham,78,Male,Saint Lucia,New York,Mayberg,john50@allen-cain.net,2022-05-07,Banned,...,10,2025-06-12,2025-07-01,UPI,4.6,NaN,VIP,NaT,App,1775.10
195,6824,Unknown,2,Male,Grenada,Vermont,Brownland,vlove@yahoo.com,2022-05-06,NaN,...,19,2025-05-13,2025-06-26,up,0.6,Author Republican region because ball note.,VIP,2025-07-23,web,2148.33
227,7986,Gregory Caldwell,41,Female,Ethiopia,Maine,Durhamport,maria61@yahoo.com,2025-02-06,Active,...,15,2025-08-21,2025-09-15,UPI,2.8,Risk focus member this.,VIP,2025-08-31,Web,5073.00
228,9044,Kevin Douglas,72,Female,Japan,Massachusetts,North Jamiehaven,thomas97@lane-gutierrez.com,2021-12-13,Active,...,4,2025-02-01,2025-03-31,UPI,3.2,Either modern anyone question.,VIP,2025-06-12,Web,1001.52
230,7644,Kayla West,95,Female,Luxembourg,Arizona,South Juan,westjoshua@crawford.org,2025-06-01,Banned,...,18,2025-06-04,2025-07-20,Debit,2.1,Century watch physical sea affect four chair.,VIP,2025-08-31,Phone,5415.12
263,4899,Renee Campbell,53,Female,Nepal,Nevada,New Joshua,hubbardjill@williams.info,2022-02-08,Banned,...,11,2025-02-06,2025-03-20,Crdit,1.3,Eight miss customer say audience those.,VIP,2025-09-25,web,9514.01
274,7892,Unknown,25,Male,Bolivia,Idaho,West Michael,jennifer19@hart-peterson.org,2023-01-11,Banned,...,20,2025-03-29,2025-10-11,Debit,4.7,Federal professor player attention end.,VIP,NaT,app,6144.80
302,706,Allison Jones,70,Male,Sierra Leone,Maryland,Tinachester,sandra22@yahoo.com,2022-03-15,Active,...,6,2025-05-12,2025-08-03,up,2.5,Enough church hospital heart professional almo...,VIP,2025-08-19,Web,4873.62
390,6877,Stephanie Cummings,10,Female,Nicaragua,Oregon,Kelseyview,vincentpayne@barrett.com,2021-03-01,Banned,...,18,2025-02-06,2025-05-20,Cash,2.7,Usually air record simply style civil stock.,VIP,2025-08-08,Phone,14011.56
409,6097,Susan Phillips,89,Female,Nigeria,NaN,East Chloe,lynncox@heath-shepherd.com,2021-07-10,NaN,...,16,2025-03-18,2025-07-03,UPI,3.1,Should sign church eye relationship.,VIP,2025-02-04,web,3769.60
509,3311,William Smith,6,Female,Cote d'Ivoire,NaN,North Maryport,ginawilliamson@hotmail.com,2023-06-17,Active,...,10,2025-04-07,2025-09-19,Debit,5.3,Half dark attention daughter read simply memor...,VIP,2025-08-20,app,7953.10
539,2320,Ann Garcia,47,Male,Solomon Islands,South Carolina,West Jessicaport,fluna@gmail.com,2025-01-01,Inactive,...,12,2025-01-14,2025-08-11,Credit,0.7,NaN,VIP,2025-04-12,App,2611.08
554,7773,Maxwell Webb,46,Female,Hong Kong,Florida,New Theresaville,timothywillis@yahoo.com,2025-10-11,Banned,...,5,2025-03-30,2025-04-30,Crdit,1.6,Degree build into nor.,VIP,2025-08-26,app,1779.15
591,521,Melissa Oconnor,47,Female,Guadeloupe,South Carolina,Tracymouth,msmith@bowers.org,2024-01-05,Active,...,12,2025-09-13,2025-09-14,Credit,5.5,Under door able onto at how officer.,VIP,2025-07-11,App,5526.24
672,1482,Blake Jones,62,Female,Grenada,Maine,Tranbury,brittanygarcia@baker.com,2024-03-17,Active,...,18,2025-03-07,2025-09-06,Cash,0.3,Field maybe cultural meeting answer.,VIP,NaT,App,4118.94
848,334,Jeremy Duncan,51,Male,Antarctica (the territory South of 60 deg S),Idaho,Darrenberg,bharper@yahoo.com,2022-05-24,Active,...,19,2025-03-19,2025-10-12,up,1.0,Director race open low at word throw.,VIP,2025-02-03,web,10235.68
850,2090,Eric Shah DDS,14,Male,Djibouti,NaN,Port Sue,christopherrasmussen@hill.info,2024-11-18,Inactive,...,12,2025-05-01,2025-05-19,up,3.9,Agree among everything answer.,VIP,2025-09-30,Phone,10948.68
859,3393,Jeremy Rodriguez,55,Male,Romania,Virginia,South Kelly,butlercarol@yahoo.com,2025-05-07,Inactive,...,20,2025-02-15,2025-06-26,up,1.0,Story test civil.,VIP,2025-05-30,Phone,7344.40
866,5036,William Campbell,2,Female,Czech Republic,NaN,Pamelaborough,michellefrank@gmail.com,2022-08-28,Inactive,...,17,2025-03-20,2025-06-28,Debit,5.5,NaN,VIP,2025-05-13,app,9353.74
1185,7915,Melissa Hughes,73,Female,Somalia,North Carolina,Lake Randallmouth,ylutz@ramos.com,2020-10-14,Active,...,15,2025-05-14,2025-08-14,Credit,5.4,Visit political group situation book everythin...,VIP,2025-01-10,app,10672.50
1299,576,Dr. Ronald Simmons II,40,Female,Afghanistan,NaN,Port Erica,ereed@anderson.com,2021-10-08,NaN,...,2,2025-01-23,2025-09-17,up,1.1,NaN,VIP,2025-05-25,Phone,1016.74
1312,9437,Kevin Morales,110,Other,Albania,Illinois,Port Michael,tknight@gmail.com,2022-08-29,NaN,...,19,2025-04-11,2025-07-22,Credit,2.0,Mean become dinner discover affect law.,VIP,2025-09-08,App,9585.50
1499,7202,Erica Odonnell,75,Other,Reunion,Illinois,Wareshire,lhughes@hotmail.com,2020-03-16,Banned,...,4,2025-01-12,2025-06-04,Debit,5.1,Firm already develop result.,VIP,NaT,web,3074.28
1686,579,Jeremy Mayo,30,Other,Bosnia and Herzegovina,Alaska,Dennisland,devonhoover@johnson.com,2023-12-10,Banned,...,14,2025-05-25,2025-06-10,Crdit,4.9,NaN,VIP,2025-01-22,app,12697.58
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,UPI,4.1,NaN,VIP,NaT,App,7556.40
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80

In [ ]:
df[df["Account_Status"] == "Banned"]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
17,5598,Michelle Case,6,Other,NaN,Montana,Christopherfurt,sullivanjared@hotmail.com,2025-07-29,Banned,...,17,2025-01-03,2025-09-04,Debit,3.9,Describe again response machine remember.,VIP,2025-09-22,App,11291.74
23,7144,Edgar Hughes,10,Male,Japan,Maryland,Michelleberg,nbrooks@yahoo.com,2023-07-16,Banned,...,11,2025-05-24,2025-09-25,Debit,3.0,Machine memory girl short budget.,NaN,2025-05-04,web,1978.13
24,1619,Michael Shelton,11,Other,Mauritania,Idaho,Johnsonbury,jasonthomas@everett.com,2022-11-15,Banned,...,8,2025-04-12,2025-06-02,Cash,1.7,Analysis article sometimes Mr.,New,2025-02-21,web,7102.96
31,116,Kathy Hernandez,103,Female,Lebanon,North Dakota,Barreramouth,jmoon@fitzpatrick.com,2021-02-23,Banned,...,5,2025-08-07,2025-09-23,up,3.8,Store base opportunity yeah activity.,New,2025-05-23,Web,3578.55
43,1738,James Haas,54,Male,Mauritania,New York,Lake Amandafort,ebrown@martinez.net,2020-06-20,Banned,...,9,2025-06-21,2025-08-22,Debit,2.4,There draw recent company deal.,New,2025-03-17,Phone,6598.80
52,1962,Unknown,66,Other,Cape Verde,NaN,Joneshaven,pmorales@mclean-palmer.org,2022-02-12,Banned,...,20,2025-06-15,2025-06-15,Cash,4.8,Second girl write hope.,Returning,NaT,App,1659.00
67,7677,Brittany Brown DDS,65,Male,NaN,Louisiana,Victorialand,austinrobinson@hotmail.com,2023-12-21,Banned,...,10,2025-01-06,2025-08-25,Credit,5.6,Pressure several state campaign hot throw fact.,Returning,2025-05-08,App,8314.90
83,1957,Jessica Warner,70,Male,Mozambique,Ohio,North Ericside,roberta73@yahoo.com,2020-11-15,Banned,...,6,2025-08-16,2025-10-12,up,5.9,Create choice rich ok show.,Returning,2025-04-25,Web,3001.74
95,6505,Olivia Riley,103,Female,Afghanistan,Wyoming,Robertshaven,pcook@morgan.com,2021-06-12,Banned,...,11,2025-05-20,2025-10-07,Cash,1.7,NaN,New,2025-05-25,App,9206.01
98,7079,Katie Chavez,17,Female,Serbia,Arizona,Codybury,csmith@yahoo.com,2020-05-24,Banned,...,1,2025-02-20,2025-03-11,Cash,3.2,Walk the police remember physical at education.,VIP,2025-03-25,Phone,335.75
103,1139,Danielle Perez,88,Female,Venezuela,Colorado,Kellyshire,watkinsbenjamin@hotmail.com,2023-09-04,Banned,...,16,2025-01-13,2025-09-25,Cash,2.9,Beat everybody future member father free yet.,NaN,NaT,web,6683.20
110,6005,Nicole Dougherty,71,Other,Spain,Oklahoma,Meyerhaven,michaelpayne@melton.com,2022-03-04,Banned,...,7,2025-09-06,2025-10-08,Credit,2.4,Accept hold outside ball.,NaN,2025-06-29,App,2337.44
116,5166,Unknown,18,Male,Burkina Faso,Tennessee,South Logan,tannermichelle@hotmail.com,2025-06-09,Banned,...,1,2025-06-06,2025-08-26,Credit,1.6,Kitchen method five so minute method me.,Returning,2025-01-31,Phone,402.98
128,3471,Frederick Pierce,108,Female,Australia,Pennsylvania,Denisefurt,ocooke@yahoo.com,2024-03-25,Banned,...,8,2025-03-13,2025-03-27,UPI,4.7,Sort draw hot threat such Republican society o...,NaN,2025-07-22,app,2557.20
132,5445,Christopher Taylor,61,Other,Antarctica (the territory South of 60 deg S),Delaware,North Candiceshire,matthew90@baker-butler.com,2021-03-25,Banned,...,2,2025-06-14,2025-07-22,Cash,0.2,NaN,VIP,2025-06-19,Web,1585.76
153,454,Meghan Bowen,44,Female,Norfolk Island,California,Yolandabury,dgaines@gmail.com,2023-02-05,Banned,...,15,2025-01-01,2025-08-17,up,3.7,NaN,NaN,2025-08-20,App,7222.65
189,5574,Cynthia Cunningham,78,Male,Saint Lucia,New York,Mayberg,john50@allen-cain.net,2022-05-07,Banned,...,10,2025-06-12,2025-07-01,UPI,4.6,NaN,VIP,NaT,App,1775.10
224,2870,Monica Weiss,119,Other,Malawi,Montana,North Meganland,pamela97@blake.biz,2023-03-15,Banned,...,6,2025-08-29,2025-09-25,UPI,0.8,Probably end coach stage pick yard direction.,New,2025-10-07,Phone,1421.34
230,7644,Kayla West,95,Female,Luxembourg,Arizona,South Juan,westjoshua@crawford.org,2025-06-01,Banned,...,18,2025-06-04,2025-07-20,Debit,2.1,Century watch physical sea affect four chair.,VIP,2025-08-31,Phone,5415.12
263,4899,Renee Campbell,53,Female,Nepal,Nevada,New Joshua,hubbardjill@williams.info,2022-02-08,Banned,...,11,2025-02-06,2025-03-20,Crdit,1.3,Eight miss customer say audience those.,VIP,2025-09-25,web,9514.01
270,6156,Angela Rodriguez,18,Male,Saint Lucia,Connecticut,Port Nicholas,josephlamb@yahoo.com,2020-07-29,Banned,...,3,2025-01-18,2025-02-17,Cash,0.3,NaN,NaN,2025-04-03,web,2522.97
274,7892,Unknown,25,Male,Bolivia,Idaho,West Michael,jennifer19@hart-peterson.org,2023-01-11,Banned,...,20,2025-03-29,2025-10-11,Debit,4.7,Federal professor player attention end.,VIP,NaT,app,6144.80
282,6201,Unknown,68,Male,Tuvalu,Maryland,Port Michaelchester,fishermicheal@johnson.net,2025-06-01,Banned,...,15,2025-06-03,2025-08-13,UPI,5.2,College organization choice turn enjoy process...,Returning,2025-08-17,Web,5720.70
390,6877,Stephanie Cummings,10,Female,Nicaragua,Oregon,Kelseyview,vincentpayne@barrett.com,2021-03-01,Banned,...,18,2025-02-06,2025-05-20,Cash,2.7,Usually air record simply style civil stock.,VIP,2025-08-08,Phone,14011.56
392,1070,Mr. David Harris,60,Male,Mali,NaN,Annview,hoffmanlaura@lee.com,2025-01-20,Banned,...,12,2025-01-19,2025-07-30,UPI,0.2,Man control beyond firm huge finish industry.,NaN,2025-06-20,app,9184.56
444,7806,Ernest Kirby,71,Other,Hong Kong,South Dakota,West Janetburgh,lcosta@yahoo.com,2020-07-23,Banned,...,18,2025-04-08,2025-06-22,Credit,4.7,NaN,New,2025-06-03,Web,9969.66
554,7773,Maxwell Webb,46,Female,Hong Kong,Florida,New Theresaville,timothywillis@yahoo.com,2025-10-11,Banned,...,5,2025-03-30,2025-04-30,Crdit,1.6,Degree build into nor.,VIP,2025-08-26,app,1779.15
611,3143,Kathleen Gibbs,7,Other,Somalia,Rhode Island,Matthewton,smithsonya@mann-lee.net,2023-10-12,Banned,...,10,2025-01-27,2025-09-30,Debit,2.6,Stop item them industry report.,Returning,2025-03-28,web,7154.30
663,5344,Carolyn Clayton,103,Male,Andorra,Texas,Allisonhaven,barry51@russell-jones.net,2020-06-10,Banned,...,9,2025-06-22,2025-09-27,Credit,3.9,This kitchen receive community.,Returning,2025-09-17,app,5535.36
812,2120,Joseph Benjamin,54,Male,Algeria,Colorado,Arnoldview,howetanner@gmail.com,2020-02-19,Banned,...,15,2025-07-17,2025-10-12,Debit,2.9,Than either itself give still.,NaN,2025-04-02,Phone,6113.85
951,3998,Becky Alexander,111,Male,Marshall Islands,NaN,Charleneburgh,nicholsemily@gray-francis.net,2022-02-28,Banned,...,9,2025-04-16,2025-09-03,Debit,5.5,Interview art real fish sit get measure.,Returning,2025-01-02,app,3993.48
985,989,Kevin Wood,114,Other,Congo,Oregon,Randolphside,rday@yahoo.com,2022-06-27,Banned,...,6,2025-04-05,2025-05-20,Crdit,4.0,Allow majority increase.,New,2025-06-25,Phone,487.20
1214,4168,Alison Kelly,20,Female,Palestinian Territory,Colorado,Brownfurt,erictaylor@gmail.com,2023-04-11,Banned,...,10,2025-08-30,2025-09-23,up,2.1,Religious write health city color.,New,2025-09-06,App,5307.30
1219,2840,Mr. Richard Benton,108,Female,Moldova,Oklahoma,Jasonstad,anthonybowen@hotmail.com,2021-09-02,Banned,...,9,2025-03-31,2025-06-14,Crdit,3.6,Clearly business hair pretty.,Returning,NaT,app,8200.08
1235,2762,Steven Roach,47,Female,Latvia,Texas,Davidchester,amy28@small-graves.com,2023-05-20,Banned,...,5,2025-01-13,2025-03-08,Credit,5.8,Stock image authority particularly state.,New,2025-03-10,Web,487.10
1499,7202,Erica Odonnell,75,Other,Reunion,Illinois,Wareshire,lhughes@hotmail.com,2020-03-16,Banned,...,4,2025-01-12,2025-06-04,Debit,5.1,Firm already develop result.,VIP,NaT,web,3074.28
1615,7675,Kyle Watts,105,Male,Andorra,Hawaii,East Elizabeth,josephwhite@gmail.com,2022-04-26,Banned,...,3,2025-06-25,2025-10-12,Cash,4.7,Why address see work.,New,NaT,App,2300.55
1686,579,Jeremy Mayo,30,Other,Bosnia and Herzegovina,Alaska,Dennisland,devonhoover@johnson.com,2023-12-10,Banned,...,14,2025-05-25,2025-06-10,Crdit,4.9,NaN,VIP,2025-01-22,app,12697.58
1950,2268,Derek Martinez,116,Male,Antarctica (the territory South of 60 deg S),Missouri,South Douglasbury,timothypeters@yahoo.com,2020-07-26,Banned,...,8,2025-01-10,2025-05-22,Cash,2.1,Concern lose group different.,VIP,2025-03-16,web,2666.80
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56
3298,5796,Angel Hood,53,Male,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [ ]:
df[(df['Delivery_Date'] - df['Purchase_Date']).dt.days > 7]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56
3034,3786,Karen Miller,22,Female,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaT,web,6547.95
3298,5796,Angel Hood,53,Male,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [ ]:
df[df["Category"] == "Electronics"]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
46,2379,Tina Raymond,15,Female,Cameroon,Missouri,Chadfurt,wmoss@contreras.com,2024-01-26,Inactive,...,7,2025-04-16,2025-08-10,Credit,2.5,Record rate down economy.,New,2025-03-20,Phone,2366.56
70,7091,Unknown,50,Female,Myanmar,Kentucky,Port Kendra,zmiller@hotmail.com,2022-01-17,NaN,...,10,2025-06-18,2025-08-31,Credit,0.1,Course positive new fire sell policy.,VIP,2025-01-25,App,3098.20
92,2201,Claire Williams,38,Female,Niue,Rhode Island,Perezfurt,epetersen@yahoo.com,2023-11-04,Active,...,16,2025-01-02,2025-03-04,up,1.6,Well service body sense contain not some.,NaN,2025-07-25,App,8293.28
97,8075,John Greer,12,Female,Philippines,Illinois,New Nicholastown,sarahdyer@matthews-li.com,2021-06-22,Inactive,...,11,2025-04-07,2025-08-12,up,2.7,Art current should off include support give.,Returning,2025-04-07,App,7260.44
98,7079,Katie Chavez,17,Female,Serbia,Arizona,Codybury,csmith@yahoo.com,2020-05-24,Banned,...,1,2025-02-20,2025-03-11,Cash,3.2,Walk the police remember physical at education.,VIP,2025-03-25,Phone,335.75
108,9347,James Peterson,109,Female,Kenya,Rhode Island,Port Davidshire,vrice@gmail.com,2025-03-31,Inactive,...,2,2025-07-18,2025-07-30,Debit,1.4,NaN,New,2025-08-17,App,1797.08
110,6005,Nicole Dougherty,71,Other,Spain,Oklahoma,Meyerhaven,michaelpayne@melton.com,2022-03-04,Banned,...,7,2025-09-06,2025-10-08,Credit,2.4,Accept hold outside ball.,NaN,2025-06-29,App,2337.44
128,3471,Frederick Pierce,108,Female,Australia,Pennsylvania,Denisefurt,ocooke@yahoo.com,2024-03-25,Banned,...,8,2025-03-13,2025-03-27,UPI,4.7,Sort draw hot threat such Republican society o...,NaN,2025-07-22,app,2557.20
150,8471,Keith Reyes,24,Female,Uzbekistan,NaN,Lake Kristin,villajohn@taylor.com,2025-04-30,NaN,...,9,2025-04-11,2025-09-07,Cash,0.1,Field sell we.,Returning,2025-07-10,App,3128.49
181,8501,Robert Skinner,63,Female,Eritrea,New York,West Michelefort,warrenpatricia@young.com,2022-08-29,Inactive,...,16,2025-05-11,2025-08-19,UPI,5.8,Friend level mind someone hit paper these.,Returning,2025-07-04,App,12533.92
189,5574,Cynthia Cunningham,78,Male,Saint Lucia,New York,Mayberg,john50@allen-cain.net,2022-05-07,Banned,...,10,2025-06-12,2025-07-01,UPI,4.6,NaN,VIP,NaT,App,1775.10
190,483,Shelly Frederick,12,Male,Uruguay,Connecticut,West Michael,jessewilkinson@yahoo.com,2024-07-21,Active,...,18,2025-03-10,2025-05-26,Credit,0.6,Down wish meet outside environment forget.,Returning,2025-07-26,app,8373.06
212,580,Hayley Martinez,65,Male,United Arab Emirates,Nevada,Gonzalezmouth,george57@reed-park.info,2021-02-03,Active,...,11,2025-04-09,2025-06-10,Credit,3.4,NaN,NaN,2025-03-16,app,6303.55
228,9044,Kevin Douglas,72,Female,Japan,Massachusetts,North Jamiehaven,thomas97@lane-gutierrez.com,2021-12-13,Active,...,4,2025-02-01,2025-03-31,UPI,3.2,Either modern anyone question.,VIP,2025-06-12,Web,1001.52
235,2230,Carol Lyons,2,Female,Somalia,California,Butlershire,jacksonmatthew@yahoo.com,2021-03-14,Inactive,...,1,2025-03-03,2025-07-19,Cash,2.0,NaN,Returning,2025-05-31,App,326.12
274,7892,Unknown,25,Male,Bolivia,Idaho,West Michael,jennifer19@hart-peterson.org,2023-01-11,Banned,...,20,2025-03-29,2025-10-11,Debit,4.7,Federal professor player attention end.,VIP,NaT,app,6144.80
302,706,Allison Jones,70,Male,Sierra Leone,Maryland,Tinachester,sandra22@yahoo.com,2022-03-15,Active,...,6,2025-05-12,2025-08-03,up,2.5,Enough church hospital heart professional almo...,VIP,2025-08-19,Web,4873.62
429,1003,Jennifer Phillips,93,Female,Macao,NaN,New Joannatown,williamjarvis@yahoo.com,2020-10-16,NaN,...,10,2025-07-10,2025-09-14,Crdit,5.3,Budget wife audience again special full young.,NaN,2025-06-30,app,4344.30
490,611,Mark Orozco,46,Male,Costa Rica,NaN,Aliciatown,wpacheco@miller-young.biz,2021-04-15,NaN,...,8,2025-08-26,2025-10-01,up,1.4,Write realize if computer student.,NaN,2025-09-12,web,199.12
509,3311,William Smith,6,Female,Cote d'Ivoire,NaN,North Maryport,ginawilliamson@hotmail.com,2023-06-17,Active,...,10,2025-04-07,2025-09-19,Debit,5.3,Half dark attention daughter read simply memor...,VIP,2025-08-20,app,7953.10
533,8660,Jeffery Stark,35,Male,Saint Martin,Maryland,Charlesport,darin66@gross-chapman.org,2022-04-28,NaN,...,5,2025-03-28,2025-04-07,UPI,3.8,Stuff wish bar question.,NaN,2025-02-22,app,587.25
539,2320,Ann Garcia,47,Male,Solomon Islands,South Carolina,West Jessicaport,fluna@gmail.com,2025-01-01,Inactive,...,12,2025-01-14,2025-08-11,Credit,0.7,NaN,VIP,2025-04-12,App,2611.08
601,8499,Robert Boyd,19,Female,Greece,Oregon,West Jocelynberg,andersoncharles@gmail.com,2021-03-07,NaN,...,10,2025-01-05,2025-01-23,Cash,1.8,Design bag property board movie parent.,NaN,2025-09-16,Web,2636.60
641,4956,Kristen Ellison,26,Female,Seychelles,Tennessee,Lake Austinhaven,tgutierrez@gmail.com,2023-11-14,Inactive,...,6,2025-02-25,2025-08-22,Crdit,2.8,Person start support American action.,Returning,2025-10-08,App,2434.44
647,1914,Kristen Martinez,29,Other,Zambia,Tennessee,Schmidtport,wilsonkimberly@hotmail.com,2020-12-05,Inactive,...,18,2025-08-06,2025-08-25,Debit,0.3,Up practice she.,New,NaT,app,9672.84
672,1482,Blake Jones,62,Female,Grenada,Maine,Tranbury,brittanygarcia@baker.com,2024-03-17,Active,...,18,2025-03-07,2025-09-06,Cash,0.3,Field maybe cultural meeting answer.,VIP,NaT,App,4118.94
695,9025,Christopher Hernandez,47,Female,Guadeloupe,Arkansas,Bartonfort,warrentanya@hotmail.com,2020-03-20,Active,...,7,2025-06-05,2025-06-21,Cash,3.9,Officer do however base will this chance.,NaN,2025-06-23,web,6468.63
743,415,Andrea Martinez,102,Female,Australia,Kentucky,Nicoleside,duncanjeremy@yahoo.com,2021-11-15,Active,...,8,2025-02-24,2025-09-04,Debit,1.2,Into whose reach coach too.,NaN,2025-03-31,Web,5209.60
789,5267,Angela Lewis,46,Other,Solomon Islands,NaN,Freemanbury,caitlin16@frederick-wyatt.com,2021-10-17,Active,...,3,2025-04-24,2025-04-27,Cash,0.9,Stand conference husband other left into.,NaN,2025-08-08,Phone,2064.12
795,5410,Diana Goodwin,99,Male,Niger,California,Kellyborough,brownkeith@green-wilkins.com,2020-03-01,NaN,...,10,2025-01-16,2025-06-23,Crdit,3.3,Dog catch here scientist community recent.,Returning,NaT,Web,7352.80
848,334,Jeremy Duncan,51,Male,Antarctica (the territory South of 60 deg S),Idaho,Darrenberg,bharper@yahoo.com,2022-05-24,Active,...,19,2025-03-19,2025-10-12,up,1.0,Director race open low at word throw.,VIP,2025-02-03,web,10235.68
866,5036,William Campbell,2,Female,Czech Republic,NaN,Pamelaborough,michellefrank@gmail.com,2022-08-28,Inactive,...,17,2025-03-20,2025-06-28,Debit,5.5,NaN,VIP,2025-05-13,app,9353.74
899,9425,Carrie Campbell,85,Female,Malta,Utah,East Diane,uarnold@yahoo.com,2020-05-10,Active,...,8,2025-03-19,2025-09-15,Cash,4.8,Arm experience call meeting.,Returning,2025-08-05,App,4421.12
1219,2840,Mr. Richard Benton,108,Female,Moldova,Oklahoma,Jasonstad,anthonybowen@hotmail.com,2021-09-02,Banned,...,9,2025-03-31,2025-06-14,Crdit,3.6,Clearly business hair pretty.,Returning,NaT,app,8200.08
1235,2762,Steven Roach,47,Female,Latvia,Texas,Davidchester,amy28@small-graves.com,2023-05-20,Banned,...,5,2025-01-13,2025-03-08,Credit,5.8,Stock image authority particularly state.,New,2025-03-10,Web,487.10
1615,7675,Kyle Watts,105,Male,Andorra,Hawaii,East Elizabeth,josephwhite@gmail.com,2022-04-26,Banned,...,3,2025-06-25,2025-10-12,Cash,4.7,Why address see work.,New,NaT,App,2300.55
1686,579,Jeremy Mayo,30,Other,Bosnia and Herzegovina,Alaska,Dennisland,devonhoover@johnson.com,2023-12-10,Banned,...,14,2025-05-25,2025-06-10,Crdit,4.9,NaN,VIP,2025-01-22,app,12697.58
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,UPI,4.1,NaN,VIP,NaT,App,7556.40
2131,5006,Phillip Graves,46,Male,NaN,Hawaii,Thompsonland,patrickjohnson@hotmail.com,2021-02-17,Active,...,13,2025-02-23,2025-08-06,Debit,0.5,Man Congress officer room allow.,Returning,2025-02-26,Web,3579.55
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56
3034,3786,Karen Miller,22,Female,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaT,web,6547.95

In [ ]:
df[df["Country"] == "India"]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
154,2027,Richard Harris,35,Female,India,Wyoming,North Ericshire,lisa42@yahoo.com,2025-08-11,Inactive,...,11,2025-05-25,2025-07-22,UPI,4.2,Different explain something though know ball r...,New,2025-02-04,app,2670.69

In [ ]:
df[df['Quantity'] > 10]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
14,8372,Samuel Mcgee,0,Male,Martinique,New Jersey,Burkechester,tyler96@hotmail.com,2023-11-01,Active,...,18,2025-07-07,2025-09-24,Debit,2.2,Term meeting one statement role long campaign.,New,2025-03-11,Phone,4285.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1756,5178,Robert Price,113,Other,Isle of Man,Colorado,Robertsberg,englishdiane@guzman-schneider.com,2021-04-30,Inactive,...,15,2025-03-23,2025-06-29,UPI,4.1,NaN,VIP,NaT,App,7556.40
2131,5006,Phillip Graves,46,Male,NaN,Hawaii,Thompsonland,patrickjohnson@hotmail.com,2021-02-17,Active,...,13,2025-02-23,2025-08-06,Debit,0.5,Man Congress officer room allow.,Returning,2025-02-26,Web,3579.55
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56
3034,3786,Karen Miller,22,Female,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaT,web,6547.95
3298,5796,Angel Hood,53,Male,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [ ]:
df[df['Discount'] > 50]

Empty DataFrame
Columns: [Customer_ID, Name, Age, Gender, Country, State, City, Email, Signup_Date, Account_Status, Product_ID, Product_Name, Category, Price, Discount, Quantity, Purchase_Date, Delivery_Date, Payment_Type, Feedback_Score, Comments, Customer_Loyalty, Last_Login, Signup_Channel, Total_Purchase]
Index: []

[0 rows x 25 columns]

In [ ]:
df[df['Price'] * df['Quantity'] > 1000]

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Quantity,Purchase_Date,Delivery_Date,Payment_Type,Feedback_Score,Comments,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase
0,1191,Larry Wallace,31,Other,NaN,Arkansas,Janetfort,gonzalezbrandi@shaffer-lambert.com,2021-05-23,Inactive,...,12,2025-04-04,2025-09-10,up,4.7,During about main range.,NaN,2025-07-23,Web,7394.28
1,8287,Shawn Palmer,20,Male,Uganda,Texas,Smithhaven,davidmendoza@hotmail.com,2025-05-18,NaN,...,9,2025-01-23,2025-05-29,Cash,4.2,Beat increase state especially society color.,Returning,2025-02-21,Web,5083.20
10,1379,Louis Cuevas,83,Male,Germany,Idaho,Samanthachester,yvonne52@hall.com,2020-08-02,NaN,...,15,2025-07-15,2025-09-08,Credit,4.9,Suddenly hold power wall daughter least enviro...,New,2025-05-11,Web,6366.75
11,7739,Tracy Reed,109,Male,Hong Kong,Mississippi,New Jamieland,erica26@yahoo.com,2021-09-03,NaN,...,18,2025-04-10,2025-08-03,Crdit,4.8,Morning bed perhaps check dream make year.,New,2025-09-16,app,4852.26
13,211,Lynn Garcia,15,Male,Rwanda,Nebraska,Lake Michael,ocruz@yahoo.com,2020-08-19,Active,...,14,2025-05-14,2025-10-12,Credit,2.7,Now seem could training behavior.,New,2025-01-01,app,4000.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2175,3253,Erin Goodwin,58,Male,Antigua and Barbuda,New Mexico,Kimstad,brose@chavez.com,2023-12-15,NaN,...,5,2025-03-28,2025-09-05,Crdit,1.8,Son night international next project.,Returning,2025-05-14,App,3143.80
2240,8324,Michael Lee,110,Female,Afghanistan,California,Robinberg,mariamoyer@yahoo.com,2020-01-08,Inactive,...,3,2025-04-27,2025-08-24,up,2.0,Direction former win who choose party summer s...,NaN,2025-09-28,web,2697.84
2417,3364,Timothy Miller,9,Male,Germany,Arkansas,Morganhaven,bthomas@evans.com,2023-05-13,Banned,...,12,2025-04-06,2025-09-18,UPI,2.0,NaN,New,2025-05-04,app,5458.56
3034,3786,Karen Miller,22,Female,France,NaN,West Brenda,zsmall@gmail.com,2023-05-20,NaN,...,15,2025-07-06,2025-08-26,UPI,5.1,Live assume test hear debate theory market.,New,NaT,web,6547.95
3298,5796,Angel Hood,53,Male,NaN,Arkansas,Lake Derek,omar32@yahoo.com,2021-08-19,Banned,...,15,2025-03-10,2025-06-25,Debit,5.8,Popular second song compare.,New,2025-02-28,app,4152.90

In [ ]:
df['Total_Purchase'] = df['Price'] * df['Quantity']

In [ ]:
df['Discounted_Price'] = df['Price'] - df['Discount']

In [ ]:
df['Delivery_Duration'] = (df['Delivery_Date'] - df['Purchase_Date']).dt.days

In [ ]:
bins = [0, 12, 19, 59, 120]
labels = ['Child','Teen','Adult','Senior']
df['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=labels)

In [ ]:
df['Loyalty_Level'] = pd.qcut(df['Total_Purchase'], q=3, labels=['Low','Medium','High'])

In [ ]:
df['Gender_Code'] = df['Gender'].map({'Male':1,'Female':2}).fillna(3)

In [ ]:
df['Account_Code'] = df['Account_Status'].map({'Active':1,'Inactive':2,'Banned':3})

In [ ]:
df['Country'] = df['Country'].str.title()

In [ ]:
df['Payment_Type'] = df['Payment_Type'].str.title()

In [ ]:
df = df.applymap(lambda x: x.strip().lower() if isinstance(x, str) else x)

/tmp/ipython-input-1274793226.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip().lower() if isinstance(x, str) else x)

In [ ]:
df.groupby('Product_ID')['Total_Purchase'].sum().nlargest(5)

Product_ID
316    150510.44
447    146885.46
44     145095.84
68     143621.63
489    130886.80
Name: Total_Purchase, dtype: float64

In [ ]:
df.groupby('Customer_ID')['Total_Purchase'].sum().nlargest(5)

Customer_ID
2157    52557.35
4678    45326.89
1492    42178.21
4316    41073.12
7746    38760.93
Name: Total_Purchase, dtype: float64

In [ ]:
df.groupby('Category')['Discount'].mean()

Category
clothing       19.256855
electronics    19.930981
misc           19.426081
Name: Discount, dtype: float64

In [ ]:
df.groupby('Category')['Feedback_Score'].mean()

Category
clothing       3.022495
electronics    3.026078
misc           2.994045
Name: Feedback_Score, dtype: float64

In [ ]:
df['Payment_Type'].value_counts().idxmax()

'upi'

In [ ]:
df.loc[df['Total_Purchase'].idxmax(), 'Customer_ID']

np.int64(7924)

In [ ]:
df['Customer_ID'].value_counts()[df['Customer_ID'].value_counts() > 5]

Customer_ID
8429    7
4367    6
7157    6
5841    6
5675    6
Name: count, dtype: int64

In [ ]:
df.sort_values('Delivery_Duration', ascending=False)

,Customer_ID,Name,Age,Gender,Country,State,City,Email,Signup_Date,Account_Status,...,Customer_Loyalty,Last_Login,Signup_Channel,Total_Purchase,Discounted_Price,Delivery_Duration,Age_Group,Loyalty_Level,Gender_Code,Account_Code
1364,8989,kevin walsh,61,f,burundi,massachusetts,lake allison,xwheeler@yahoo.com,2022-07-30,inactive,...,vip,2025-03-29,app,8798.13,NaN,278,senior,high,3.0,2.0
5839,4567,mallory martinez,48,female,NaN,north carolina,jonesborough,vmason@rodriguez.com,2022-03-23,active,...,returning,NaT,app,-4818.40,970.72,278,adult,low,2.0,1.0
5095,2276,annette hernandez,37,female,venezuela,maine,port collinberg,lmadden@yahoo.com,2022-07-26,inactive,...,new,2025-06-21,app,1334.79,120.02,278,adult,medium,2.0,2.0
3972,2058,rebecca schmidt,109,male,lao people's democratic republic,NaN,south bradleychester,NaN,2025-10-08,NaN,...,NaN,2025-04-08,web,983.28,249.58,276,senior,medium,1.0,NaN
383,7338,eric strong,23,mle,antigua and barbuda,massachusetts,lake justin,jacksonmichael@bell-adams.com,2022-10-02,NaN,...,returning,2025-03-28,app,-0.00,-69.12,275,adult,low,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6595,3219,david sanchez,36,other,tonga,ohio,colemanstad,gary03@rowland-jennings.info,2021-07-26,active,...,new,2025-05-01,web,58.92,NaN,-274,adult,low,3.0,1.0
2350,8909,jacqueline ross,26,other,holy see (vatican city state),indiana,johnport,johnsonzachary@harrison.com,2020-08-18,inactive,...,returning,2025-09-26,web,-463.82,195.71,-274,adult,low,3.0,2.0
42,7532,sandra evans,10,other,vanuatu,montana,raymondstad,nicholas79@finley.com,2024-06-02,NaN,...,returning,2025-07-06,web,6507.16,570.83,-279,child,high,3.0,NaN
6354,3077,sara watkins,62,male,georgia,utah,terryburgh,gstephens@kim.info,2020-02-20,banned,...,new,2025-05-09,app,-366.40,39.64,-279,senior,low,1.0,3.0
6838,465,NaN,82,f,comoros,kentucky,haleland,NaN,2025-04-23,NaN,...,vip,2025-03-31,phone,521.91,493.74,-281,senior,medium,3.0,NaN

In [ ]:
df.loc[df['Feedback_Score'].idxmax()], df.loc[df['Feedback_Score'].idxmin()]

(Customer_ID                                                7391
 Name                                              alice bentley
 Age                                                          90
 Gender                                                      mle
 Country                                                    guam
 State                                                    hawaii
 City                                           west michaeltown
 Email                                       alawson@hotmail.com
 Signup_Date                                 2021-10-04 00:00:00
 Account_Status                                         inactive
 Product_ID                                                  320
 Product_Name                                               lead
 Category                                                   misc
 Price                                                    270.44
 Discount                                                    NaN
 Quantity                                                      8
 Purchase_Date                               2025-01-03 00:00:00
 Delivery_Date                               2025-02-09 00:00:00
 Payment_Type                                                upi
 Feedback_Score                                              6.0
 Comments             house red degree choose mother peace fear.
 Customer_Loyalty                                            NaN
 Last_Login                                  2025-08-19 00:00:00
 Signup_Channel                                              app
 Total_Purchase                                          2163.52
 Discounted_Price                                            NaN
 Delivery_Duration                                            37
 Age_Group                                                senior
 Loyalty_Level                                            medium
 Gender_Code                                                 3.0
 Account_Code                                                2.0
 Name: 63, dtype: object,
 Customer_ID                                  5304
 Name                               david holloway
 Age                                            30
 Gender                                       male
 Country                                 nicaragua
 State                                     montana
 City                                    nancybury
 Email                angelaanthony@carpenter.info
 Signup_Date                   2022-12-11 00:00:00
 Account_Status                             banned
 Product_ID                                    206
 Product_Name                                 then
 Category                                     misc
 Price                                       48.82
 Discount                                    21.57
 Quantity                                       20
 Purchase_Date                 2025-08-24 00:00:00
 Delivery_Date                 2025-05-19 00:00:00
 Payment_Type                                 cash
 Feedback_Score                                0.0
 Comments                       field why his age.
 Customer_Loyalty                        returning
 Last_Login                    2025-09-21 00:00:00
 Signup_Channel                                app
 Total_Purchase                              976.4
 Discounted_Price                            27.25
 Delivery_Duration                             -97
 Age_Group                                   adult
 Loyalty_Level                              medium
 Gender_Code                                   1.0
 Account_Code                                  3.0
 Name: 249, dtype: object)

In [ ]:
df.groupby(['Country','Category'])['Total_Purchase'].sum().reset_index()

         Country     Category  Total_Purchase
0    afghanistan     clothing        10926.08
1    afghanistan  electronics        20519.32
2    afghanistan         misc        63391.79
3        albania     clothing        48820.78
4        albania  electronics        35575.69
..           ...          ...             ...
724       zambia  electronics        44273.01
725       zambia         misc        30677.41
726     zimbabwe     clothing        44590.88
727     zimbabwe  electronics        60527.83
728     zimbabwe         misc        27229.12

[729 rows x 3 columns]